name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-latest:
    name: Build and run unit tests with latest Go 1.x
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make

      - name: Test
        run: make test

  test-release:
    name: Build and run unit tests with Go 1.20
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make

      - name: Test
        run: make test
